# Generated by Django 5.2.5 on 2025-09-27 18:50

import backend.api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'business_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessIdea',
            fields=[
                ('idea_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target_audience', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=64)),
                ('business_type', models.CharField(max_length=64)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'business_idea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvestorDetails',
            fields=[
                ('investor_id', models.AutoField(primary_key=True, serialize=False)),
                ('investor_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('verification_status', models.CharField(default='pending', max_length=64)),
                ('email_address', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'investor_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvestorInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'investor_interest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('role', models.CharField(blank=True, default='', max_length=80)),
                ('verify_type', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'db_table': 'api_investorprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvestorVerificationDoc',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=backend.api.models.investor_doc_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_investorverificationdoc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(db_column='resource_id', primary_key=True, serialize=False)),
                ('category_id', models.IntegerField(db_column='category_id')),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description', default='')),
                ('website', models.CharField(blank=True, db_column='website', default='', max_length=255)),
                ('location', models.CharField(blank=True, db_column='location', default='', max_length=255)),
                ('geo_data', models.CharField(blank=True, db_column='geo_data', default='', max_length=128)),
                ('type', models.CharField(db_column='type', db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'resource',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(db_column='role_id', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='role_name', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(db_column='user_role_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('suggestions', models.JSONField(blank=True, default=list, null=True)),
                ('risks', models.JSONField(blank=True, default=list, null=True)),
                ('roadmap', models.JSONField(blank=True, default=list, null=True)),
                ('kpis', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(db_column='competitor_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('strength', models.TextField(blank=True)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='competitors', to='api.businesscategory')),
            ],
            options={
                'db_table': 'competitor',
            },
        ),
    ]
