# Generated by Django 5.2.5 on 2025-09-14 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_investorprofile_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='verify_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='InvestorVerificationDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='investor_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='api.investorprofile')),
            ],
        ),
    ]
