# Generated by Django 5.2.5 on 2025-09-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_investorprofile_verify_type_investorverificationdoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(db_column='role_id', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='role_name', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(db_column='user_role_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_role',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='investorprofile',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='investorverificationdoc',
            options={'managed': False},
        ),
    ]
