# Generated by Django 5.2.5 on 2025-09-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_role_userrole_alter_investorprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('WHOLESALE', 'Wholesale'), ('OFFICE', 'Office'), ('TRANSPORT', 'Transport'), ('SECURITY', 'Security'), ('SAAS', 'SaaS')], db_index=True, max_length=20)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('geo_data', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelTable(
            name='investorprofile',
            table='api_investorprofile',
        ),
        migrations.AlterModelTable(
            name='investorverificationdoc',
            table='api_investorverificationdoc',
        ),
    ]
