# Generated by Django 5.2.5 on 2025-09-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_resource_alter_investorprofile_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('WHOLESALE', 'Wholesale'), ('OFFICE', 'Office'), ('TRANSPORT', 'Transport'), ('SECURITY', 'Security'), ('IT_SECURITY', 'IT Security')], db_index=True, max_length=20),
        ),
    ]
