# Generated by Django 5.2.5 on 2025-09-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('SECURITY', 'Security'), ('WHOLESALE', 'Wholesale'), ('OFFICE', 'Office'), ('TRANSPORT', 'Transport'), ('SAAS', 'SaaS')], db_index=True, max_length=20),
        ),
    ]
