# Generated by Django 5.2.5 on 2025-09-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_resource_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'managed': False, 'ordering': ['name']},
        ),
    ]
