# Generated by Django 5.2.5 on 2025-09-18 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_resource_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'business_category',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='resource',
            table='resource',
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(db_column='competitor_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('strength', models.TextField(blank=True)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='competitors', to='api.businesscategory')),
            ],
            options={
                'db_table': 'competitor',
            },
        ),
    ]
