# Generated by Django 5.2.5 on 2025-09-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_businesscategory_alter_resource_table_competitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIdea',
            fields=[
                ('idea_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('target_audience', models.TextField(blank=True)),
                ('location_scope', models.CharField(blank=True, max_length=64)),
                ('business_type', models.CharField(blank=True, max_length=64)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'business_idea',
                'managed': False,
            },
        ),
    ]
