# Generated by Django 5.2.5 on 2025-09-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_businessidea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessidea',
            options={},
        ),
        migrations.AlterModelTable(
            name='investorprofile',
            table='investor_details',
        ),
    ]
